#You can eidt the color scheme in source/css/_base/variable.styl

photo: /image/me.jpg

email: jiaoew2011@gmail.com
twitter:
facebook: enwei.jiao
googleplus:
github: jiaoew1991
pinterest:
linkedin:
instagram:
zhihu: jiao-en-wei
weibo:
renren:


addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

#
bighomepage: true

google_analytics:
rss: /atom.xml

forvirgo: true
